import fs from "node:fs";
import { Scoreboard, HEADLINE_CUT } from "./backtest";
import { ENTRANTS } from "./rank";

const START = "<!-- SCOREBOARD:START -->",
  END = "<!-- SCOREBOARD:END -->";
const pct = (x: number) => (x * 100).toFixed(1) + "%";

/** The README scoreboard is generated, never typed (idea borrowed from live-leaderboard repos). CI fails if it goes stale. */
export function scoreboardMarkdown(boards: Scoreboard[]): string {
  const h = String(HEADLINE_CUT);
  const ids = ["B0", ...Object.keys(ENTRANTS)];
  const head = `| Subject | Test sittings | ${ids.join(" | ")} | Verdict |\n|---|---|${ids.map(() => "---").join("|")}|---|`;
  const rows = boards.map(
    (b) =>
      `| ${b.subject}${b.synthetic ? " **(SYNTHETIC)**" : ""} | ${b.n_test} | ${ids.map((id) => (b.n_test ? pct(b.summary[id].mean[h]) : "-")).join(" | ")} | ${b.headline.verdict} |`,
  );
  return [
    `_Mean marks coverage when studying only the top ${HEADLINE_CUT * 100}% of each list (by topic count), walk-forward. Generated by \`kya readme\` - do not edit by hand._`,
    "",
    head,
    ...rows,
    "",
    "B0 random · B1 syllabus order · B2 last paper first · **B3 ours: total past marks** · C1 recency challenger · C2 gap-aware challenger",
  ].join("\n");
}
export function injectScoreboard(readmePath: string, boards: Scoreboard[], check = false): boolean {
  const text = fs.readFileSync(readmePath, "utf8");
  const a = text.indexOf(START),
    b = text.indexOf(END);
  if (a < 0 || b < 0) throw new Error(`README is missing the ${START} / ${END} markers`);
  const next = text.slice(0, a + START.length) + "\n" + scoreboardMarkdown(boards) + "\n" + text.slice(b);
  if (check) return next === text;
  fs.writeFileSync(readmePath, next);
  return true;
}
